#!/bin/bash

set -eo pipefail

# Add pantheon git remote
PANTHEON_REPO=$(terminus connection:info $TERMINUS_SITE.dev --field=git_url)
git remote add pantheon $PANTHEON_REPO

# Push code to Pantheon
git fetch pantheon
git pull pantheon --all
git pull pantheon --tags
git push origin -all
git push origin -tags

# Clean up
git remote remove pantheon