#!/bin/bash

set -eo pipefail

#
# This script starts up the test process.
#
# - Environment settings (e.g. git config) are initialized
# - Terminus plugins are installed
# - Any needed code updates are done
#
echo "Begin build for $DEFAULT_ENV. Pantheon test environment is $TERMINUS_SITE.$TERMINUS_ENV"

# Log in via Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

# Switch connection mode to Git
terminus connection:set $TERMINUS_SITE.dev git

# Add pantheon git remote
PANTHEON_REPO=$(terminus connection:info $TERMINUS_SITE.dev --field=git_url)
git remote add pantheon $PANTHEON_REPO

# Push code to Pantheon
if [ -n "$CIRCLE_TAG" ]
then
  echo "Pushing ${CIRCLE_TAG} tag to pantheon"
  git push --force pantheon "refs/tags/${CIRCLE_TAG}"
elif [ -n "$CIRCLE_BRANCH" ]
then
  echo "Pushing ${CIRCLE_BRANCH} branch to pantheon"
  git push --force pantheon $CIRCLE_BRANCH
fi

# Clean up
git remote remove pantheon

# Run updatedb on the dev environment
# terminus -n env:wake "$TERMINUS_SITE.dev"
# terminus -n drush $TERMINUS_SITE.dev -- updatedb --yes
# terminus -n drush $TERMINUS_SITE.dev -- cc all --yes