#!/bin/bash

set -eo pipefail

# Log in via Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

# Switch connection mode to Git
terminus connection:set $TERMINUS_SITE.dev git

# Add pantheon git remote
PANTHEON_REPO=$(terminus connection:info $TERMINUS_SITE.dev --field=git_url)
git remote add --mirror=fetch pantheon $PANTHEON_REPO

# Push code to Pantheon
git fetch repo1 --tags
# git pull pantheon --tags
# git push origin -all
# git push origin -tags

# Clean up
git remote remove pantheon