#!/bin/bash

set -eo pipefail

echo "Begin downtstream sync to GitHub"

# Log in via Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

# Switch connection mode to Git
terminus connection:set $TERMINUS_SITE.dev git

# Add pantheon git remote
PANTHEON_REPO=$(terminus connection:info $TERMINUS_SITE.dev --field=git_url)
git remote add pantheon $PANTHEON_REPO

# Push code to Pantheon
git fetch pantheon --tags
git push --force origin --all
git push --force origin --tags

# Clean up
git remote remove pantheon